name: Info Board
main: me.xxsniperzzxxsd.infoboard.Main
version: 0.1.1
author: xXSniperzzXx_SD
description: Show an info board
softdepend: [Essentials, Factions, Infected, Jobs, LWC, mcMMO, MCTowns, PlotMe, TownyVariables, WorldGuard]

commands:
    InfoBoard:
        usage: /<command>
        description: The main command for this plugin
        aliases: [IB]
        
permissions:
    InfoBoard.*:
        default: op
        children:
            InfoBoard.Set: true
            InfoBoard.Toggle: true
            InfoBoard.Reload: true
    InfoBoard.View:
        default: true