name: Info Board
main: me.xxsniperzzxxsd.infoboard.Main
version: 0.1.4
author: SniperzCiinema
description: Show an info board
softdepend: [Cranked, Essentials, Factions, Heroes, Infected, Jobs, LWC, mcMMO, McTowns, MiniGames, PlotMe, Stats, Towny, WorldGuard, AncientRPG]

commands:
    InfoBoard:
        usage: /<command>
        description: The main command for this plugin
        aliases: [IB]
        
permissions:
    InfoBoard.*:
        default: op
        children:
            InfoBoard.Set: true
            InfoBoard.Toggle: true
            InfoBoard.Reload: true
    InfoBoard.View:
        default: true